### PR TITLE
Update to modern Rust

### PR DESCRIPTION
**Pull request by jonas-schievink**
This kind of got out of hand, but SprocketNES now compiles with the newest Rust nightly, beta and stable.

I've also updated the directory structure (following the Cargo guide), and split the project into a library and a binary (which I'm not sure makes much sense now, but if someone crazy wants to use this in something like a multi-emulator, this will make it like 1% easier).

Oh, and I've enabled V-Sync, which made a massive difference for me (games were massively stuttering before).

### CODE REVIEW

**Comment by Byron** [comment]
+1

It works relatively fine already, even though some Roms crash outright (contra), or do so when trying to start the game (super mario bros. 3, Legend of Zelda).

**Comment by jonas-schievink** [comment]
Contra crashes because mapper 2 isn't implemented. I've actually done this in my `mapper2` branch and Contra works with it (as does Castlevania), although save states seem to mess up the game (I think save state handling could use an overhaul).

I'm not sure what causes the other crashes, but I'm suspecting that PPU emulation isn't 100% accurate, so that could cause some glitches and crashes.

**Comment by Byron** [comment]
Considering the project started out as a Rust-demo many years ago, you did amazing work already. I wished there was a dedicated maintainer, like the [gameboy emulator](https://github.com/Gekkio/mooneye-gb) project has.

If you would be interested in stepping in, maybe @pcwalton would make you a collaborator ?

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/kVFndwzRGv8).

*`Looksies #9 [Let's look at the sprocketnes]`*

[\thumb](https://youtu.be/kVFndwzRGv8)

**Comment by pcwalton** [comment]
Wow! Reviewing now.

**Comment by pcwalton** [comment]
Looks good. Thanks!

**Pull request merged**
